---
kind: pipeline
type: docker
name: compliance

trigger:
  branch:
    include:
      - develop
      - main

steps:
  - name: lint-server
    image: node:16
    commands:
      - ./scripts/lint-server.sh
  - name: lint-console
    image: node:16
    commands:
      - ./scripts/lint-console.sh
  - name: lint-frontend
    image: node:16
    commands:
      - ./scripts/lint-frontend.sh
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
      event:
        exclude:
          - pull_request

---
kind: pipeline
type: docker
name: testing-linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    include:
      - develop
      - main

depends_on:
  - compliance

steps:
  - name: test-server-node-12
    image: node:12
    commands:
      - cd server
      - npm ci --unsafe-perm
      - npm test
  - name: test-server-node-14
    image: node:14
    commands:
      - cd server
      - npm ci --unsafe-perm
      - npm test
  - name: test-server-node-16
    image: node:16
    commands:
      - cd server
      - npm ci
      - npm test
  - name: docker-testimage
    pull: always
    image: plugins/docker:latest
    settings:
      repo: registry.abrain.dev:5000/alarmdisplay/display
      registry: registry.abrain.dev:5000
      tags: testing-amd64
    environment:
      DOCKER_PASSWORD:
        from_secret: tmpregistry_password
      DOCKER_USERNAME:
        from_secret: tmpregistry_username
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
      event:
        exclude:
          - pull_request
---
kind: pipeline
type: docker
name: docker-linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    include:
      - develop
      - main

depends_on:
  - testing-linux-amd64

services:
  - name: mariadb
    image: mariadb
    pull: if-not-exists
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_DATABASE: display
  - name: sut
    image: registry.abrain.dev:5000/alarmdisplay/display:testing-amd64
    pull: always
    environment:
      MYSQL_URI: mysql://root:@mariadb:3306/display

steps:
  - name: test-api
    image: node:16
    commands:
      - cd test-api
      - npm ci
      - SERVER_URL=http://sut:3031 npm start
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_hook
    when:
      status:
        - failure
      event:
        exclude:
          - pull_request

image_pull_secrets:
  - dockerconfig
---
kind: signature
hmac: 5c24fe648b22c819ed631ea95d43b04478787fd111433fbd0333203cb3d2739b

...
