---
kind: pipeline
type: docker
name: compliance

trigger:
  branch:
    include:
      - develop
      - main

steps:
  - name: lint-server
    image: node:20.12.2
    commands:
      - ./scripts/lint-server.sh
  - name: lint-console
    image: node:20.12.2
    commands:
      - ./scripts/lint-console.sh
  - name: lint-frontend
    image: node:20.12.2
    commands:
      - ./scripts/lint-frontend.sh

---
kind: pipeline
type: docker
name: testing-linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    include:
      - develop
      - main

depends_on:
  - compliance

steps:
  - name: test-server-node-18
    image: node:18.19.1
    commands:
      - cd server
      - npm ci
      - npx jest --runInBand --forceExit
  - name: test-server-node-20
    image: node:20.12.2
    environment:
      CC_TEST_REPORTER_ID:
        from_secret: cc_test_reporter_id
    commands:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - cd server
      - npm ci
      - npx jest --runInBand --forceExit --coverage
      - ../scripts/report-code-coverage.sh

---
kind: signature
hmac: fcbc8133f92e5ae0dd7a7c707a120a72eec3962c750c3691ea94f13b0dad0c5f

...
