---
kind: pipeline
type: docker
name: compliance

trigger:
  branch:
    include:
      - develop
      - main

steps:
  - name: lint-server
    image: node:18.19.1
    commands:
      - ./scripts/lint-server.sh
  - name: lint-console
    image: node:18.19.1
    commands:
      - ./scripts/lint-console.sh
  - name: lint-frontend
    image: node:18.19.1
    commands:
      - ./scripts/lint-frontend.sh

---
kind: pipeline
type: docker
name: testing-linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    include:
      - develop
      - main

depends_on:
  - compliance

steps:
  - name: test-server-node-16
    image: node:16.20.2
    commands:
      - cd server
      - npm ci
      - npx jest --runInBand --forceExit
  - name: test-server-node-18
    image: node:18.19.1
    environment:
      CC_TEST_REPORTER_ID:
        from_secret: cc_test_reporter_id
    commands:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - cd server
      - npm ci
      - npx jest --runInBand --forceExit --coverage
      - ../scripts/report-code-coverage.sh

---
kind: signature
hmac: 7e8a0682d42d2e98e981647f763fbf73278710ece1ed961f92fadd4154fd33c9

...
