FROM node:20.16.0@sha256:d3c8ababe9566f9f3495d0d365a5c4b393f607924647dd52e75bf4f8a54effd3

WORKDIR /home/node/app
COPY ./build/package.json ./build/package-lock.json /home/node/app/
RUN npm ci --only=production --no-audit
COPY ./build /home/node/app

EXPOSE 3031
ENV NODE_ENV production
ENV NODE_CONFIG_ENV docker
USER node
CMD [ "node", "index.js" ]
