FROM node:20.18.0@sha256:196a5fcd13db4362fb9c0ec5391db36ec954c65d6b0d0e5d37f59c7dc9920690

WORKDIR /home/node/app
COPY ./build/package.json ./build/package-lock.json /home/node/app/
RUN npm ci --only=production --no-audit
COPY ./build /home/node/app

EXPOSE 3031
ENV NODE_ENV production
ENV NODE_CONFIG_ENV docker
USER node
CMD [ "node", "index.js" ]
