FROM node:20.18.0@sha256:a7a3b7ec6de4b11bb2d673b31de9d28c6da09c557ee65453672c8e4f754c23fc

WORKDIR /home/node/app
COPY ./build/package.json ./build/package-lock.json /home/node/app/
RUN npm ci --only=production --no-audit
COPY ./build /home/node/app

EXPOSE 3031
ENV NODE_ENV production
ENV NODE_CONFIG_ENV docker
USER node
CMD [ "node", "index.js" ]
