import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowsAlt,
  faBars,
  faBullhorn,
  faChevronLeft,
  faChevronRight,
  faClock,
  faCloudShowersHeavy,
  faCog,
  faColumns,
  faCube,
  faCubes,
  faDesktop,
  faEdit,
  faEnvelope,
  faExpandAlt,
  faHome,
  faInfoCircle,
  faKey,
  faLock,
  faPencilAlt,
  faPlus,
  faQuestionCircle,
  faSignOutAlt,
  faSpinner,
  faStopwatch,
  faTabletAlt,
  faTimes,
  faTrashAlt,
  faUser,
  faUserEdit,
  faUserMinus,
  faUserPlus,
  faWrench
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(
  faArrowsAlt,
  faBars,
  faBullhorn,
  faChevronLeft,
  faChevronRight,
  faClock,
  faCloudShowersHeavy,
  faCog,
  faColumns,
  faCube,
  faCubes,
  faDesktop,
  faEdit,
  faEnvelope,
  faExpandAlt,
  faHome,
  faInfoCircle,
  faKey,
  faLock,
  faPencilAlt,
  faPlus,
  faQuestionCircle,
  faSignOutAlt,
  faSpinner,
  faStopwatch,
  faTabletAlt,
  faTimes,
  faTrashAlt,
  faUser,
  faUserEdit,
  faUserMinus,
  faUserPlus,
  faWrench
)

export default FontAwesomeIcon
