# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI for Server

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

defaults:
  run:
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:11.8.7@sha256:78185355dd49b54dd6909072531ce8d7e06aa0eccd7aa5b23c93ebb7e34c5aaa
        env:
          MARIADB_USER: display
          MARIADB_PASSWORD: display
          MARIADB_ROOT_PASSWORD: doesntmatter
          MARIADB_DATABASE: display
          TZ: Europe/Berlin
        ports:
          - 3306/tcp
        options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: 'server/.nvmrc'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - run: npm ci
    - run: npm run lint
    - run: npm run compile
    - run: npm run jest -- --coverage
      env:
        MYSQL_URI: mysql://display:display@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/display

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ${{github.workspace}}/server/coverage
        flags: server
