# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI for Server

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

defaults:
  run:
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:11.8.6@sha256:31c1aa20ba2d78c4cbc45b2675e40ffd6a3cd59897a9767ce88fc284309f55ab
        env:
          MARIADB_USER: display
          MARIADB_PASSWORD: display
          MARIADB_ROOT_PASSWORD: doesntmatter
          MARIADB_DATABASE: display
          TZ: Europe/Berlin
        ports:
          - 3306/tcp
        options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: 'server/.nvmrc'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    - run: npm ci
    - run: npm run lint
    - run: npm run compile
    - run: npm run jest -- --coverage
      env:
        MYSQL_URI: mysql://display:display@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/display

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ${{github.workspace}}/server/coverage
        flags: server
